#!/usr/bin/env python3
"""Copy the version from pyproject.toml (the single source) into
docs/version.js, which the About dialog reads. `--check` only compares, for
CI."""

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
VERSION_JS = ROOT / "docs" / "version.js"


def main():
    version = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]
    wanted = ('// Generated by `make update_version` from pyproject.toml; do not edit.\n'
              f'export const CRYSVIZ_VERSION = "{version}";\n')
    current = VERSION_JS.read_text(encoding="utf-8") if VERSION_JS.exists() else None
    if current == wanted:
        return 0
    if sys.argv[1:] == ["--check"]:
        print(f"docs/version.js does not match version {version} in pyproject.toml.")
        print("You need to run `make update_version`")
        return 1
    VERSION_JS.write_text(wanted, encoding="utf-8")
    print(f"updated docs/version.js to {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
