#!/usr/bin/env python3
"""Copy the version from pyproject.toml (the single source) into the files
that cannot read it themselves: src/crysviz/__init__.py and docs/version.js
(read by the About dialog). `--check` only compares, for CI."""

import re
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
INIT = ROOT / "src" / "crysviz" / "__init__.py"
VERSION_JS = ROOT / "docs" / "version.js"
INIT_RE = re.compile(r'^__version__ = "[^"]*"$', re.M)


def main():
    check = sys.argv[1:] == ["--check"]
    version = tomllib.loads((ROOT / "pyproject.toml").read_text(encoding="utf-8"))["project"]["version"]

    init_text = INIT.read_text(encoding="utf-8")
    wanted = {
        INIT: INIT_RE.sub(f'__version__ = "{version}"', init_text, count=1),
        VERSION_JS: f'// Generated by `make update_version` from pyproject.toml; do not edit.\nexport const CRYSVIZ_VERSION = "{version}";\n',
    }
    stale = [p for p, text in wanted.items() if not p.exists() or p.read_text(encoding="utf-8") != text]

    if check:
        if stale:
            print(f"Version {version} in pyproject.toml is not in: "
                  + ", ".join(str(p.relative_to(ROOT)) for p in stale))
            print("You need to run `make update_version`")
            return 1
        return 0
    for path in stale:
        path.write_text(wanted[path], encoding="utf-8")
        print(f"updated {path.relative_to(ROOT)} to {version}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
