/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const __wbg_periodicresult_free: (a: number, b: number) => void;
export const __wbg_polyhedraresult_free: (a: number, b: number) => void;
export const compute_polyhedra: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number, m: number, n: number, o: number, p: number, q: number, r: number, s: number, t: number, u: number, v: number, w: number, x: number, y: number, z: number) => number;
export const periodic_wrapped: (a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number, j: number, k: number, l: number) => number;
export const periodicresult_cart: (a: number) => [number, number];
export const periodicresult_elements: (a: number) => [number, number];
export const periodicresult_frac: (a: number) => [number, number];
export const periodicresult_len: (a: number) => number;
export const periodicresult_src_index: (a: number) => [number, number];
export const polyhedraresult_accept_ms: (a: number) => number;
export const polyhedraresult_cage_band_ms: (a: number) => number;
export const polyhedraresult_cage_nloop_ms: (a: number) => number;
export const polyhedraresult_cage_pool_ms: (a: number) => number;
export const polyhedraresult_cages_ms: (a: number) => number;
export const polyhedraresult_center_src: (a: number) => [number, number];
export const polyhedraresult_centered_ms: (a: number) => number;
export const polyhedraresult_color_elem: (a: number) => [number, number];
export const polyhedraresult_count: (a: number) => number;
export const polyhedraresult_kinds: (a: number) => [number, number];
export const polyhedraresult_setup_ms: (a: number) => number;
export const polyhedraresult_vert_counts: (a: number) => [number, number];
export const polyhedraresult_vertex_srcs: (a: number) => [number, number];
export const polyhedraresult_vertices: (a: number) => [number, number];
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_start: () => void;
